version: '3.8'

services:
    laravel_app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - USER_ID=1000
                - GROUP_ID=1000
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - laravel_db
        networks:
            - laravel_network
        entrypoint: ["sh", "-c", "docker/php/entrypoint.sh php-fpm"]

    laravel_db:
        image: postgres:16
        container_name: laravel_db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=laravel_database
            - POSTGRES_USER=laravel_username
            - POSTGRES_PASSWORD=laravel_password
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel_network

    laravel_nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel_app
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
